#ifndef DEFINE_H
#define DEFINE_H

//IO DEFINE
#define VOLTSENSE A3
#define DIR 4
#define MOTION 2
#define IR 3
#define LED 7

//SENSOR DEFINE
#define OCCUPYSENSORADDRESS 0x10
#define OCCUPYSENSORTYPE 12

#define SENSOR_CHANGE_ADDRESS 10
#define SENSOR_CHANGE_SCANRATE 11
#define SENSOR_SET_LED 12

#define VOLT_AVG 10

#define SENSOR_SCAN_EN 1//Sensor Scan Enable
#define SENSOR_LED_CONTROL 2//LED Control
#define SENSOR_MOTION 3

#define SENSORSCANRATE 2
#define SENSORTESTTIMEMULTIPLYER 1000

#endif